import Head from "next/head";

import type { GetServerSidePropsContext } from "next";
import type { FC } from "react";
import type { Profile } from "~/types";

import Body from "~/components/body";
import ProfileCard from "~/components/shops/profile-card";

const ProfilePage: FC<{ data: Profile }> = ({ data }) => {
  return (
    <>
      <Head>
        <title>Profile | Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <ProfileCard className="mx-auto  h-full " {...data} />
      </Body>
    </>
  );
};

export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
  const data = {
    id: "dabls",
    owner_name: "Olayami Dabls",
    business_name: "Dabls' MBAD African Bead Museum",
    website: "http://www.mbad.org/",
    profile_photo: "/img/demo/profile_dabls.jpg",
    bio: `Detroit storyteller, Olayami Dabls, came to the corner of Grand River and West Grand Boulevard with a vision to create a space
          for his community to understand the immense power of their African heritage. Occupying almost an entire city block,
          the Dabls Mbad African Bead Museum houses 18 outdoor installations as well as the African Bead Gallery, N'kisi House and
          African Language Wall. Born of his own visual cosmology, Dabls' MBAD African Bead Museum is a quiet revolution that sparks
          a vital conversation with global and local audiences.`,
  };
  return {
    props: {
      data,
    },
  };
};
export default ProfilePage;
