import Head from "next/head";

import Body from "~/components/body";

const CollectiveAgreementPage = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy | Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <article className="prose lg:prose-xl">
          <h3 id="privacy">Artisanal Futures Collective Agreement</h3>
          <h4 id="what-information-do-we-collect">
            Work in progress. Check back soon!
          </h4>
        </article>
      </Body>
    </>
  );
};

export default CollectiveAgreementPage;
