import Head from "next/head";
import Body from "~/components/body";

const CookiePolicyPage = () => {
  return (
    <>
      <Head>
        <title>Cookie Policy - Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <article className="prose lg:prose-lg">
          <h1>Cookie Policy</h1>
          <p>Last updated: February 20th, 2024</p>
          <h2>Introduction</h2>
          <p>
            Welcome to Artisanal Futures&apos; Cookie Policy. By using our
            website and services, including our application, &quot;Solidarity
            Pathways&quot;, you agree to the use of cookies as described in this
            policy.
          </p>
          <h2>What are Cookies?</h2>
          <p>
            Cookies are small text files that are placed on your device when you
            visit a website. They are commonly used to make websites work more
            efficiently and to provide information to website owners.
          </p>
          <h2>How We Use Cookies</h2>
          <p>
            At Artisanal Futures, we use cookies primarily for authentication
            purposes within our application, &quot;Solidarity Pathways&quot;.
            These cookies are essential for ensuring the security of our
            users&apos; accounts and for enabling access to the features and
            functionalities of our app.
          </p>
          <h2>Types of Cookies We Use</h2>
          <ul>
            <li>
              <span className="font-bold">Authentication Cookies</span>:These
              cookies are used to authenticate new users and drivers accessing
              our app, &quot;Solidarity Pathways&quot;. They enable users to
              securely log in to their accounts and access our services.
            </li>
          </ul>
          <h2>Changes to This Policy</h2>
          <p>
            We may update this Cookie Policy from time to time to reflect
            changes in our practices or for other operational, legal, or
            regulatory reasons. We encourage you to review this policy
            periodically for any updates.
          </p>
          <h2>Contact Us</h2>
          <p>
            If you have any questions about our Cookie Policy, please contact us
            at [insert contact email].
          </p>
        </article>
      </Body>
    </>
  );
};

export default CookiePolicyPage;
