import Head from "next/head";
import Body from "~/components/body";

const QuestionsPage = () => {
  return (
    <>
      {" "}
      <Head>
        <title>Help Center | Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <article className="prose lg:prose-xl">
          <h3 id="faq">Help Center</h3>
          <h4 id="this-is-a-civilized-place-for-public-discussion">
            This is a Civilized Place for Public Discussion
          </h4>
          <p>
            Please treat this discussion forum with the same respect you would a
            public park. We, too, are a shared community resource — a place to
            share skills, knowledge and interests through ongoing conversation.
          </p>
          <p>
            These are not hard and fast rules, merely guidelines to aid the
            human judgment of our community and keep this a clean and
            well-lighted place for civilized public discourse.
          </p>
          <h4 id="improve-the-discussion">Improve the Discussion</h4>
          <p>
            Help us make this a great place for discussion by always working to
            improve the discussion in some way, however small. If you are not
            sure your post adds to the conversation, think over what you want to
            say and try again later.
          </p>
          <p>
            The topics discussed here matter to us, and we want you to act as if
            they matter to you, too. Be respectful of the topics and the people
            discussing them, even if you disagree with some of what is being
            said.
          </p>
          <p>
            One way to improve the discussion is by discovering ones that are
            already happening. Spend time browsing the topics here before
            replying or starting your own, and you&apos;ll have a better chance
            of meeting others who share your interests.
          </p>
          <h4 id="be-agreeable-even-when-you-disagree">
            Be Agreeable, Even When You Disagree
          </h4>
          <p>
            You may wish to respond to something by disagreeing with it.
            That&apos;s fine. But remember to criticize ideas, not people.
            Please avoid:
          </p>
          <ul>
            <li>Name-calling</li>
            <li>Ad hominem attacks</li>
            <li>
              Responding to a post&apos;s tone instead of its actual content
            </li>
            <li>Knee-jerk contradiction</li>
          </ul>
          <p>
            Instead, provide reasoned counter-arguments that improve the
            conversation.
          </p>
          <h5 id="your-participation-counts">Your Participation Counts</h5>
          <p>
            The conversations we have here set the tone for every new arrival.
            Help us influence the future of this community by choosing to engage
            in discussions that make this forum an interesting place to be — and
            avoiding those that do not.
          </p>
          <p>
            Our forum and website provides tools that enable the community to
            collectively identify the best (and worst) contributions: bookmarks,
            likes, flags, replies, edits, and so forth. Use these tools to
            improve your own experience, and everyone else&apos;s, too.
          </p>
          <p>Let&apos;s leave our community better than we found it.</p>
          <h5 id="if-you-see-a-problem-flag-it">
            If You See a Problem, Flag It
          </h5>
          <p>
            Moderators have special authority; they are responsible for this
            forum. But so are you. With your help, moderators can be community
            facilitators, not just janitors or police.
          </p>
          <p>
            When you see bad behavior, don&apos;t reply. It encourages the bad
            behavior by acknowledging it, consumes your energy, and wastes
            everyone&apos;s time. Just flag it. If enough flags accrue, action
            will be taken, either automatically or by moderator intervention.
          </p>
          <p>
            In order to maintain our community, moderators reserve the right to
            remove any content and any user account for any reason at any time.
            Moderators do not preview new posts; the moderators and site
            operators take no responsibility for any content posted by the
            community. New members are approved for forum use when they sign up
            for an account.
          </p>
          <h5 id="always-be-civil">Always Be Civil</h5>
          <p>Nothing sabotages a healthy conversation like rudeness:</p>
          <ul>
            <li>
              Be civil. Don&apos;t post anything that a reasonable person would
              consider offensive, abusive, or hate speech.
            </li>
            <li>
              Keep it clean. Don&apos;t post anything obscene or sexually
              explicit.
            </li>
            <li>
              Respect each other. Don&apos;t harass or grief anyone, impersonate
              people, or expose their private information.
            </li>
            <li>
              Respect our forum. Don&apos;t post spam or otherwise vandalize the
              forum.
            </li>
          </ul>
          <p>
            These are not concrete terms with precise definitions — avoid even
            the appearance of any of these things. If you&apos;re unsure, ask
            yourself how you would feel if your post was featured on the front
            page of the New York Times.
          </p>
          <p>
            This is a public forum, and search engines index these discussions.
            Keep the language, links, and images safe for family and friends.
          </p>
          <h5 id="keep-it-tidy">Keep It Tidy</h5>
          <p>
            Make the effort to put things in the right place, so that we can
            spend more time discussing and less cleaning up. So:
          </p>
          <ul>
            <li>Don&apos;t start a topic in the wrong category.</li>
            <li>Don&apos;t cross-post the same thing in multiple topics.</li>
            <li>Don&apos;t post no-content replies.</li>
            <li>Don&apos;t divert a topic by changing it midstream.</li>
            <li>
              Don&apos;t sign your posts — every post has your profile
              information attached to it.
            </li>
          </ul>
          <p>Rather than posting “+1” or “Agreed”, use the Like button.</p>
          <h5 id="post-only-your-own-stuff">Post Only Your Own Stuff</h5>
          <p>
            You may not post descriptions of, links to, or methods for stealing
            someone&apos;s intellectual property (software, video, audio,
            images), or for breaking any other law.
          </p>
          <h5 id="powered-by-you">Powered by You</h5>
          <p>
            This site is operated by your friendly local staff and you, the
            community. If you have any further questions about how things should
            work here, open a new topic in the site feedback category and
            let&apos;s discuss! If there&apos;s a critical or urgent issue that
            can&apos;t be handled by a meta topic or flag, contact us via the
            staff page.
          </p>
          <h5 id="terms-of-service">Terms of Service</h5>
          <p>
            Yes, legalese is boring, but we must protect ourselves – and by
            extension, you and your data – against unfriendly folks. We have a
            Terms of Service describing your (and our) behavior and rights
            related to content, privacy, and laws. To use this service, you must
            agree to abide by our TOS.
          </p>
          <p>
            Content adopted from{" "}
            <a href="https://forum.nativesintech.org/faq">Natives in Tech</a>;{" "}
            <a href="https://opendefinition.org/licenses/cc-by-sa/">CC-BY-SA</a>
          </p>
        </article>
      </Body>
    </>
  );
};
export default QuestionsPage;
