import Head from "next/head";

import Body from "~/components/body";

const PrivacyPage = () => {
  return (
    <>
      <Head>
        <title>Privacy Policy | Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <article className="prose lg:prose-xl">
          <h3 id="privacy">Privacy</h3>
          <h4 id="what-information-do-we-collect">
            What information do we collect?
          </h4>
          <p>
            We collect information from you when you register on our site and
            gather data when you participate in the forum by reading, writing,
            and evaluating the content shared here.
          </p>
          <p>
            When registering on our site, you may be asked to enter your name
            and e-mail address. You may, however, visit our site without
            registering. Your e-mail address will be verified by an email
            containing a unique link. If that link is visited, we know that you
            control the e-mail address.
          </p>
          <p>
            When registered and posting, we record the IP address that the post
            originated from. We also may retain server logs which include the IP
            address of every request to our server.
          </p>
          <h4 id="what-do-we-use-your-information-for">
            What do we use your information for?
          </h4>
          <p>
            Any of the information we collect from you may be used in one of the
            following ways:
          </p>
          <ul>
            <li>
              To personalize your experience — your information helps us to
              better respond to your individual needs.
            </li>
            <li>
              To improve our site — we continually strive to improve our site
              offerings based on the information and feedback we receive from
              you.
            </li>
            <li>
              To improve customer service — your information helps us to more
              effectively respond to your customer service requests and support
              needs.
            </li>
            <li>
              To send periodic emails — The email address you provide may be
              used to send you information, notifications that you request about
              changes to topics or in response to your user name, respond to
              inquiries, and/or other requests or questions.
            </li>
          </ul>
          <h4 id="how-do-we-protect-your-information">
            How do we protect your information?
          </h4>
          <p>
            We implement a variety of security measures to maintain the safety
            of your personal information when you enter, submit, or access your
            personal information.
          </p>
          <h4 id="what-is-your-data-retention-policy">
            What is your data retention policy?
          </h4>
          <p>We will make a good faith effort to:</p>
          <ul>
            <li>
              Retain server logs containing the IP address of all requests to
              this server no more than 90 days.
            </li>
            <li>
              Retain the IP addresses associated with registered users and their
              posts no more than 5 years.
            </li>
          </ul>
          <h4 id="do-we-use-cookies">Do we use cookies?</h4>
          <p>
            Yes. Cookies are small files that a site or its service provider
            transfers to your computer’s hard drive through your Web browser (if
            you allow). These cookies enable the site to recognize your browser
            and, if you have a registered account, associate it with your
            registered account.
          </p>
          <p>
            We use cookies to understand and save your preferences for future
            visits and compile aggregate data about site traffic and site
            interaction so that we can offer better site experiences and tools
            in the future. We may contract with third-party service providers to
            assist us in better understanding our site visitors. These service
            providers are not permitted to use the information collected on our
            behalf except to help us conduct and improve our business.
          </p>
          <h4 id="do-we-disclose-any-information-to-outside-parties">
            Do we disclose any information to outside parties?
          </h4>
          <p>
            We do not sell, trade, or otherwise transfer to outside parties your
            personally identifiable information. This does not include trusted
            third parties who assist us in operating our site, conducting our
            business, or servicing you, so long as those parties agree to keep
            this information confidential. We may also release your information
            when we believe release is appropriate to comply with the law,
            enforce our site policies, or protect ours or others rights,
            property, or safety. However, non-personally identifiable visitor
            information may be provided to other parties for marketing,
            advertising, or other uses.
          </p>
          <h4 id="third-party-links">Third party links</h4>
          <p>
            Occasionally, at our discretion, we may include or offer third party
            products or services on our site. These third party sites have
            separate and independent privacy policies. We therefore have no
            responsibility or liability for the content and activities of these
            linked sites. Nonetheless, we seek to protect the integrity of our
            site and welcome any feedback about these sites.
          </p>
          <h4 id="childrens-online-privacy-protection-act-compliance">
            Children’s Online Privacy Protection Act Compliance
          </h4>
          <p>
            Our site, products and services are all directed to people who are
            at least 13 years old or older. If this server is in the USA, and
            you are under the age of 13, per the requirements of COPPA (
            <a href="https://en.wikipedia.org/wiki/Children%27s_Online_Privacy_Protection_Act">
              Children’s Online Privacy Protection Act
            </a>
            ), do not use this site.
          </p>
          <h4 id="online-privacy-policy-only">Online Privacy Policy Only</h4>
          <p>
            This online privacy policy applies only to information collected
            through our site and not to information collected offline.
          </p>
          <h4 id="your-consent">Your Consent</h4>
          <p>By using our site, you consent to our web site privacy policy.</p>
          <h4 id="changes-to-our-privacy-policy">
            Changes to our Privacy Policy
          </h4>
          <p>
            If we decide to change our privacy policy, we will post those
            changes on this page.
          </p>
          <p>
            Content adopted from{" "}
            <a href="https://forum.nativesintech.org/faq">Natives in Tech</a>;{" "}
            <a href="https://opendefinition.org/licenses/cc-by-sa/">CC-BY-SA</a>
          </p>
        </article>
      </Body>
    </>
  );
};
export default PrivacyPage;
