import Head from "next/head";

import Body from "~/components/body";

const TermsPage = () => {
  return (
    <>
      <Head>
        <title>Terms of Use | Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <article className="prose  lg:prose-xl">
          <h3 id="terms-of-service">Terms of Use</h3>
          <p>
            These terms govern use of the Internet forum at{" "}
            <a href="https://forum.artisanalfutures.org">
              https://forum.artisanalfutures.org
            </a>{" "}
            and <a href="http://artisanalfutures.org">artisanalfutures.org</a>{" "}
            and all subdomains. To use these, you must agree to these terms.
          </p>
          <p>
            ArtisanalFutures may offer other products and services, under
            different terms. These terms apply only when no other terms have
            been given.
          </p>
          <p>Skip to:</p>
          <ul>
            <li>Important Terms</li>
            <li>Your Permission to Use the Forum</li>
            <li>Conditions for Use of the Forum</li>
            <li>Acceptable Use</li>
            <li>Content Standards</li>
            <li>Enforcement</li>
            <li>Your Account</li>
            <li>Your Content</li>
            <li>Your Responsibility</li>
            <li>Disclaimers</li>
            <li>Limits on Liability</li>
            <li>Feedback</li>
            <li>Termination</li>
            <li>Disputes</li>
            <li>General Terms</li>
            <li>Contact</li>
            <li>Changes</li>
          </ul>
          <h4 id="important-terms">Important Terms</h4>
          <p>
            These terms include a number of important provisions that affect
            your rights and responsibilities, such as the disclaimers in
            Disclaimers, limits on ArtisanalFutures&apos;s liability to you in
            Limits on Liability, your agreement to cover ArtisanalFutures for
            damages caused by your misuse of the forum in Responsibility for
            Your Use, and an agreement to arbitrate disputes in Disputes.
          </p>
          <h4 id="your-permission-to-use-the-forum">
            Your Permission to Use the Forum
          </h4>
          <p>
            Subject to these terms, ArtisanalFutures gives you permission to use
            the forum. Everyone needs to agree to these terms to use the forum.
          </p>
          <h4 id="conditions-for-use-of-the-forum">
            Conditions for Use of the Forum
          </h4>
          <p>
            Your permission to use the forum is subject to the following
            conditions:
          </p>
          <ol>
            <li>You must be at least thirteen years old.</li>
            <li>
              You may no longer use the forum if ArtisanalFutures contacts you
              directly to say that you may not.
            </li>
            <li>
              You must use the forum in accordance with Acceptable Use and
              Content Standards.
            </li>
          </ol>
          <h4 id="acceptable-use">Acceptable Use</h4>
          <ol>
            <li>You may not break the law using the forum.</li>
            <li>
              You may not use or try to use another&apos;s account on the forum
              without their specific permission.
            </li>
            <li>
              You may not buy, sell, or otherwise trade in user names or other
              unique identifiers on the forum.
            </li>
            <li>
              You may not send advertisements, chain letters, or other
              solicitations through the forum, or use the forum to gather
              addresses or other personal data for commercial mailing lists or
              databases.
            </li>
            <li>
              You may not automate access to the forum, or monitor the forum,
              such as with a web crawler, browser plug-in or add-on, or other
              computer program that is not a web browser. You may crawl the
              forum to index it for a publicly available search engine, if you
              run one.
            </li>
            <li>
              You may not use the forum to send e-mail to distribution lists,
              newsgroups, or group mail aliases.
            </li>
            <li>
              You may not falsely imply that you&apos;re affiliated with or
              endorsed by ArtisanalFutures.
            </li>
            <li>
              You may not hyperlink to images or other non-hypertext content on
              the forum on other webpages.
            </li>
            <li>
              You may not remove any marks showing proprietary ownership from
              materials you download from the forum.
            </li>
            <li>
              You may not show any part of the forum on other websites with
              &apos;iframe&apos;.
            </li>
            <li>
              You may not disable, avoid, or circumvent any security or access
              restrictions of the forum.
            </li>
            <li>
              You may not strain the infrastructure of the forum with an
              unreasonable volume of requests, or requests designed to impose an
              unreasonable load on information systems underlying the forum.
            </li>
            <li>You may not impersonate others through the forum.</li>
            <li>
              You may not encourage or help anyone in violation of these terms.
            </li>
          </ol>
          <h4 id="content-standards">Content Standards</h4>
          <ol>
            <li>
              You may not submit content to the forum that is illegal,
              offensive, or otherwise harmful to others. This includes content
              that is harassing, inappropriate, or abusive.
            </li>
            <li>
              You may not submit content to the forum that violates the law,
              infringes anyone&apos;s intellectual property rights, violates
              anyone&apos;s privacy, or breaches agreements you have with
              others.
            </li>
            <li>
              You may not submit content to the forum containing malicious
              computer code, such as computer viruses or spyware.
            </li>
            <li>
              You may not submit content to the forum as a mere placeholder, to
              hold a particular address, user name, or other unique identifier.
            </li>
            <li>
              You may not use the forum to disclose information that you
              don&apos;t have the right to disclose, like others&apos;
              confidential or personal information.
            </li>
          </ol>
          <h4 id="enforcement">Enforcement</h4>
          <p>
            ArtisanalFutures may investigate and prosecute violations of these
            terms to the fullest legal extent. ArtisanalFutures may notify and
            cooperate with law enforcement authorities in prosecuting violations
            of the law and these terms.
          </p>
          <p>
            ArtisanalFutures reserves the right to change, redact, and delete
            content on the forum for any reason. If you believe someone has
            submitted content to the forum in violation of these terms, contact
            us immediately.
          </p>
          <h4 id="your-account">Your Account</h4>
          <p>
            You must create and log into an account to use some features of the
            forum.
          </p>
          <p>
            To create an account, you must provide some information about
            yourself. If you create an account, you agree to provide, at a
            minimum, a valid e-mail address, and to keep that address
            up-to-date. You may close your account at any time by e-mailing{" "}
            <a href="mailto:support@artisanalfutures.org">
              support@artisanalfutures.org
            </a>
            .
          </p>
          <p>
            You agree to be responsible for all action taken using your account,
            whether authorized by you or not, until you either close your
            account or notify ArtisanalFutures that your account has been
            compromised. You agree to notify ArtisanalFutures immediately if you
            suspect your account has been compromised. You agree to select a
            secure password for your account, and keep it secret.
          </p>
          <p>
            ArtisanalFutures may restrict, suspend, or close your account on the
            forum according to its policy for handling copyright-related
            takedown requests, or if ArtisanalFutures reasonably believes that
            you&apos;ve broken any rule in these terms.
          </p>
          <h4 id="your-content">Your Content</h4>
          <p>
            Nothing in these terms gives ArtisanalFutures any ownership rights
            in intellectual property that you share with the forum, such as your
            account information, posts, or other content you submit to the
            forum. Nothing in these terms gives you any ownership rights in
            ArtisanalFutures&apos;s intellectual property, either.
          </p>
          <p>
            Between you and ArtisanalFutures, you remain solely responsible for
            content you submit to the forum. You agree not to wrongly imply that
            content you submit to the forum is sponsored or approved by
            ArtisanalFutures. These terms do not obligate ArtisanalFutures to
            store, maintain, or provide copies of content you submit, and to
            change it, according to these terms.
          </p>
          <p>
            Content you submit to the forum belongs to you, and you decide what
            permission to give others for it. But at a minimum, you license
            ArtisanalFutures to provide content that you submit to the forum to
            other users of the forum. That special license allows
            ArtisanalFutures to copy, publish, and analyze content you submit to
            the forum.
          </p>
          <p>
            When content you submit is removed from the forum, whether by you or
            by ArtisanalFutures, ArtisanalFutures&apos;s special license ends
            when the last copy disappears from ArtisanalFutures&apos;s backups,
            caches, and other systems. Other licenses you apply to content you
            submit, such as Creative Commons licenses, may continue after your
            content is removed. Those licenses may give others, or
            ArtisanalFutures itself, the right to share your content through the
            forum again.
          </p>
          <p>
            Others who receive content you submit to the forum may violate the
            terms on which you license your content. You agree that
            ArtisanalFutures will not be liable to you for those violations or
            their consequences.
          </p>
          <h4 id="your-responsibility">Your Responsibility</h4>
          <p>
            You agree to indemnify ArtisanalFutures from legal claims by others
            related to your breach of these terms, or breach of these terms by
            others using your account on the forum. Both you and
            ArtisanalFutures agree to notify the other side of any legal claims
            for which you might have to indemnify ArtisanalFutures as soon as
            possible. If ArtisanalFutures fails to notify you of a legal claim
            promptly, you won&apos;t have to indemnify ArtisanalFutures for
            damages that you could have defended against or mitigated with
            prompt notice. You agree to allow ArtisanalFutures to control
            investigation, defense, and settlement of legal claims for which you
            would have to indemnify ArtisanalFutures, and to cooperate with
            those efforts. ArtisanalFutures agrees not to agree to any
            settlement that admits fault for you or imposes obligations on you
            without your prior agreement.
          </p>
          <h4 id="disclaimers">Disclaimers</h4>
          <p>
            You accept all risk of using the forum and content on the forum. As
            far as the law allows, ArtisanalFutures and its suppliers provide
            the forum as is, without any warranty whatsoever.
          </p>
          <p>
            The forum may hyperlink to and integrate forums and services run by
            others. ArtisanalFutures does not make any warranty about services
            run by others, or content they may provide. Use of services run by
            others may be governed by other terms between you and the one
            running service.
          </p>
          <h4 id="limits-on-liability">Limits on Liability</h4>
          <p>
            Neither ArtisanalFutures nor its suppliers will be liable to you for
            breach-of-contract damages their personnel could not have reasonably
            foreseen when you agreed to these terms.
          </p>
          <p>
            As far as the law allows, the total liability to you for claims of
            any kind that are related to the forum or content on the forum will
            be limited to $50.
          </p>
          <h4 id="feedback">Feedback</h4>
          <p>
            ArtisanalFutures welcomes your feedback and suggestions for the
            forum. See the Contact section below for ways to get in touch with
            us.
          </p>
          <p>
            You agree that ArtisanalFutures will be free to act on feedback and
            suggestions you provide, and that ArtisanalFutures won&apos;t have
            to notify you that your feedback was used, get your permission to
            use it, or pay you. You agree not to submit feedback or suggestions
            that you believe might be confidential or proprietary, to you or
            others.
          </p>
          <h4 id="termination">Termination</h4>
          <p>
            Either you or ArtisanalFutures may end the agreement written out in
            these terms at any time. When our agreement ends, your permission to
            use the forum also ends.
          </p>
          <p>
            The following provisions survive the end of our agreement: Your
            Content, Feedback, Your Responsibility, Disclaimers, Limits on
            Liability, and General Terms.
          </p>
          <h4 id="disputes">Disputes</h4>
          <p>
            The Artisanal Futures Collective Agreement will govern any dispute
            related to these terms or your use of the forum.
          </p>
          <p>
            You and ArtisanalFutures agree to seek injunctions related to these
            terms only in state or federal court in Oklahoma City, OK. Neither
            you nor ArtisanalFutures will object to jurisdiction, forum, or
            venue in those courts.
          </p>
          <p>
            Other than to seek an injunction or for claims under the Computer
            Fraud and Abuse Act, you and ArtisanalFutures will resolve any
            dispute by binding American Arbitration Association arbitration.
            Arbitration will follow the AAA&apos;s Commercial Arbitration Rules
            and Supplementary Procedures for Consumer Related Disputes.
            Arbitration will happen in Ann Arbor, MI. You will settle any
            dispute as an individual, and not as part of a class action or other
            representative proceeding, whether as the plaintiff or a class
            member. No arbitrator will consolidate any dispute with any other
            arbitration without ArtisanalFutures&apos;s permission.
          </p>
          <p>
            Any arbitration award will include costs of the arbitration,
            reasonable attorneys&apos; fees, and reasonable costs for witnesses.
            You and ArtisanalFutures may enter arbitration awards in any court
            with jurisdiction.
          </p>
          <h4 id="general-terms">General Terms</h4>
          <p>
            If a provision of these terms is unenforceable as written, but could
            be changed to make it enforceable, that provision should be modified
            to the minimum extent necessary to make it enforceable. Otherwise,
            that provision should be removed.
          </p>
          <p>
            You may not assign your agreement with ArtisanalFutures.
            ArtisanalFutures may assign your agreement to any affiliate of
            ArtisanalFutures, any other company that obtains control of
            ArtisanalFutures, or any other company that buys assets of
            ArtisanalFutures related to the forum. Any attempted assignment
            against these terms has no legal effect.
          </p>
          <p>
            Neither the exercise of any right under this Agreement, nor waiver
            of any breach of this Agreement, waives any other breach of this
            Agreement.
          </p>
          <p>
            These terms embody all the terms of agreement between you and
            ArtisanalFutures about use of the forum. These terms entirely
            replace any other agreements about your use of the forum, written or
            not.
          </p>
          <h4 id="contact">Contact</h4>
          <p>
            You may notify ArtisanalFutures under these terms, and send
            questions, at{" "}
            <a href="mailto:support@artistanalfutures.org">
              support@artistanalfutures.org
            </a>
            .
          </p>
          <p>
            ArtisanalFutures may notify you under these terms using the e-mail
            address you provide for your account on the forum, or by posting a
            message to the homepage of the forum or your account page.
          </p>
          <h4 id="changes">Changes</h4>
          <p>
            ArtisanalFutures last updated these terms on August 3, 2022, and may
            update these terms again. ArtisanalFutures will post all updates to
            the forum. For updates that contain substantial changes,
            ArtisanalFutures agrees to e-mail you, if you&apos;ve created an
            account and provided a valid e-mail address. ArtisanalFutures may
            also announce updates with special messages or alerts on the forum.
          </p>
          <p>
            Once you get notice of an update to these terms, you must agree to
            the new terms in order to keep using the forum.
          </p>
          <p>
            Content adopted from{" "}
            <a href="https://forum.nativesintech.org/faq">Natives in Tech</a>;{" "}
            <a href="https://opendefinition.org/licenses/cc-by-sa/">CC-BY-SA</a>
          </p>
        </article>
      </Body>
    </>
  );
};

export default TermsPage;
