import { PlusCircle } from "lucide-react";
import type { GetServerSidePropsContext } from "next";
import type { User } from "next-auth";

import Head from "next/head";
import { useEffect } from "react";
import ProfileLayout from "~/apps/account/profile-layout";
import { Button } from "~/components/ui/button";
import { Separator } from "~/components/ui/separator";
import { useShopModal } from "~/hooks/use-shop-modal";
import { prisma } from "~/server/db";
import { authenticateUserServerSide } from "~/utils/authentication/server";
export default function ProfileShopPage() {
  const onOpen = useShopModal((state) => state.onOpen);

  useEffect(() => {
    onOpen();
  }, [onOpen]);

  return (
    <>
      <Head>
        <title>New Shop | Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProfileLayout>
        <div className="space-y-6">
          <div>
            <h3 className="text-lg font-medium">Shop Dashboard</h3>
            <p className="text-sm text-muted-foreground">
              Configure how your store is shown to visitors
            </p>
          </div>
          <Separator />
          <p>
            You currently don&apos;t have a shop setup yet. Create one to
            promote your business to visitors on the site!
          </p>

          <Button onClick={onOpen} type="button">
            <PlusCircle className="mr-2 h-5 w-5" />
            Create Store
          </Button>
        </div>
      </ProfileLayout>
    </>
  );
}

const handleStoreServerSide = async (user: User) => {
  const userId = user.id;
  const shop = await prisma.shop.findFirst({
    where: {
      ownerId: userId,
    },
  });

  if (shop) {
    return {
      redirect: {
        destination: `/profile/shop/${shop.id.toString()}`,
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
};

export const getServerSideProps = async (ctx: GetServerSidePropsContext) =>
  authenticateUserServerSide(ctx, handleStoreServerSide);
