import { SignUp } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";

import AuthLayout from "~/layouts/auth-layout";
const SignUpPage = () => (
  <>
    <Head>
      <title>Artisanal Futures</title>
      <meta name="description" content="Generated by create-t3-app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <AuthLayout>
      <div className=" my-auto flex h-full w-full items-center gap-5">
        <div className="justify-left flex w-4/12">
          <SignUp path="/sign-up" routing="path" signInUrl="/sign-in" />
        </div>
        <div className=" flex w-8/12 justify-end  ">
          <Image
            src="/pancakes.svg"
            alt="under development"
            width={500}
            height={500}
          />
        </div>
      </div>
    </AuthLayout>
  </>
);

export default SignUpPage;
