import { Cog, GraduationCap, Store } from "lucide-react";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Body from "~/components/body";
import { api } from "~/utils/api";

import Hero from "~/components/homepage/hero";

import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";

export default function Home() {
  return (
    <>
      <Head>
        <title>Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <Hero />
        <div className="mt-12 grid grid-cols-1 gap-5 bg-slate-200 p-4 md:grid-cols-3 md:gap-10">
          <Link href="/shops">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 ">
                <CardTitle className="text-sm font-medium">
                  Browse our artisan&apos;s shops and sites
                </CardTitle>
                <Store className="h-8 w-8 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">Shop our Stores</div>
              </CardContent>
            </Card>
          </Link>
          <Link
            href="https://artisanal-futures-forum.vercel.app/"
            target="_blank"
          >
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">
                  Share your artisanal knowledge with others
                </CardTitle>
                <GraduationCap className="h-8  w-8  text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">Share Knowledge</div>
              </CardContent>
            </Card>
          </Link>
          <Link href="/tools">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium">
                  Use our collection of free tools
                </CardTitle>
                <Cog className="h-8  w-8  text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold">Utilize Free Tools</div>
              </CardContent>
            </Card>
          </Link>
        </div>
        <div className=" text-center">
          <h2 className="mt-12 text-3xl font-bold">
            Artisanal Technologies for Generative Justice
          </h2>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img
            src="img/flowchart.png"
            alt="Flowchart showing the generative nature of artisanal tech"
            className="w-full "
            loading="lazy"
          />
        </div>{" "}
        <AuthShowcase />
      </Body>
    </>
  );
}
function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-black">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-black no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
