import {
  Cog,
  CreditCard,
  DollarSign,
  GraduationCap,
  Package,
  Store,
  StoreIcon,
} from "lucide-react";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import { useMemo } from "react";
import Body from "~/components/body";
import Footer from "~/components/footer";
import FeatureCard from "~/components/homepage/feature-card";
import Hero from "~/components/homepage/hero";
import Navbar from "~/components/navbar";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import Container from "~/components/ui/container";
import { api } from "~/utils/api";
export default function Home() {
  return (
    <>
      <Head>
        <title>Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <Hero />
        <div className="mt-12 grid grid-cols-1 gap-5 bg-slate-200 p-4 md:grid-cols-3 md:gap-10">
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2 ">
              <CardTitle className="text-sm font-medium">
                Browse our artisan&apos;s shops and sites
              </CardTitle>
              <Store className="h-8 w-8 text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">Shop our Stores</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                Share your artisanal knowledge with others
              </CardTitle>
              <GraduationCap className="h-8  w-8  text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">Share Knowledge</div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">
                Use our collection of free tools
              </CardTitle>
              <Cog className="h-8  w-8  text-muted-foreground" />
            </CardHeader>
            <CardContent>
              <div className="text-2xl font-bold">Utilize Free Tools</div>
            </CardContent>
          </Card>
        </div>

        <div className=" text-center">
          <h2 className="mt-12 text-3xl font-bold">
            Artisanal Technologies for Generative Justice
          </h2>
          <img
            src="img/flowchart.png"
            alt="Flowchart showing the generative nature of artisanal tech"
            className="w-full "
            loading="lazy"
          />
        </div>
      </Body>
    </>
  );
}
