import Head from "next/head";
import Navbar from "~/components/admin/navbar";
import { Overview } from "~/components/admin/overview";
import { RecentMembers } from "~/components/admin/recent-members";
import Body from "~/components/body";
import { SidebarNav } from "~/components/profile/sidebar-nav";
import { Button } from "~/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Separator } from "~/components/ui/separator";

const sidebarNavItems = [
  {
    title: "Dashboard",
    href: "/admin",
  },
  {
    title: "Shops",
    href: "/admin/shops",
  },
];

interface SettingsLayoutProps {
  children: React.ReactNode;
}

export default function AdminLayout({ children }: SettingsLayoutProps) {
  return (
    <>
      <Head>
        <title>Admin | Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Body>
        <div className=" block space-y-6 py-5 pb-16">
          <div className="space-y-0.5">
            <h2 className="text-2xl font-bold tracking-tight">Admin</h2>
          </div>
          <Separator className="my-6" />
          <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
            <aside className="-mx-4 lg:w-1/5">
              <SidebarNav items={sidebarNavItems} />
            </aside>
            <div className="flex-1 lg:max-w-2xl">{children}</div>
          </div>
        </div>
      </Body> */}

      <main className="flex h-screen flex-col overflow-y-auto">
        <Navbar />
        {children}
      </main>
    </>
  );
}
