/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Link from "next/link";

const AuthLayout = ({ children }: { children: React.ReactNode }) => {
  const year = new Date().getFullYear();
  return (
    <>
      <Head>
        <title>Solidarity Pathways | Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />{" "}
        <meta
          name="viewport"
          content="width=device-width,height=device-height initial-scale=1"
        />
        <link rel="icon" href="/favicon.ico" />{" "}
      </Head>
      <main className="fixed flex h-full w-full flex-col ">
        <div className="border-b">
          <div className="relative flex h-16 items-center px-4 sm:px-6 lg:px-8">
            <Link href="/" className=" flex items-center gap-x-2 lg:ml-0">
              <img
                className="block h-5 w-auto lg:hidden"
                src="/img/logo.png"
                alt="Artisanal Futures logo"
              />
              <img
                className="hidden h-5 w-auto lg:block"
                src="/img/logo.png"
                alt="Artisanal Futures logo"
              />
            </Link>
          </div>
        </div>
        <div className="relative mx-auto flex  h-full   w-full  max-w-7xl flex-col-reverse p-2 max-md:overflow-auto md:flex-row lg:h-[calc(100vh-64px)]">
          {children}
        </div>
        <footer className=" mx-auto w-full max-w-7xl px-4 py-10 max-md:text-center">
          <p className=" text-sm text-black">
            &copy; {year} Artisanal Futures. All rights reserved.
          </p>
        </footer>{" "}
      </main>
    </>
  );
};
export default AuthLayout;
