import { useSession } from "next-auth/react";
import Head from "next/head";
import { useParams } from "next/navigation";
import { useRouter } from "next/router";
import { useMemo } from "react";

import Body from "~/components/body";
import ShopSwitcher from "~/components/profile/shop-switcher";
import { SidebarNav } from "~/components/profile/sidebar-nav";
import { Label } from "~/components/ui/label";
import PageLoader from "~/components/ui/page-loader";
import { Separator } from "~/components/ui/separator";
import { api } from "~/utils/api";

interface SettingsLayoutProps {
  children: React.ReactNode;
}

export default function ProfileLayout({ children }: SettingsLayoutProps) {
  const { data: shop } = api.shops.getCurrentUserShop.useQuery();
  const { data: sessionData, status } = useSession();
  const { data: shops } = api.shops.getAllCurrentUserShops.useQuery();
  const router = useRouter();
  const params = useParams();

  const navItems = useMemo(() => {
    return [
      {
        title: "Profile",
        href: "/profile",
      },
      shop
        ? {
            title: "Shops",
            href: `/profile/shop/${shop?.id}`,
          }
        : {
            title: "Shops",
            href: "/profile/shop",
          },
      {
        title: "Survey",
        href: "/profile/survey",
      },
    ];
  }, [shop]);

  return (
    <>
      <Head>
        <title>Profile | Artisanal Futures</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        {status === "loading" ? (
          <PageLoader />
        ) : (
          <>
            <div className=" block space-y-6 py-5 pb-16">
              <div className="flex items-center justify-between">
                <div className="space-y-0.5 ">
                  <h2 className="text-2xl font-bold tracking-tight">
                    Settings
                  </h2>
                  <p className="text-muted-foreground">
                    Manage your account settings , shop settings, and update
                    preferences.
                  </p>
                </div>

                {sessionData?.user?.role === "ADMIN" && (
                  <div className="flex flex-col space-y-1">
                    <Label>Switch Current Shop:</Label>
                    {shops && shops.length > 0 && (
                      <ShopSwitcher items={shops} />
                    )}
                  </div>
                )}
              </div>
              <Separator className="my-6" />
              <div className="flex flex-col space-y-8 lg:flex-row lg:space-x-12 lg:space-y-0">
                <aside className="-mx-4 lg:w-1/5">
                  <SidebarNav items={navItems} />
                </aside>
                <div className="flex-1 lg:max-w-2xl">{children}</div>
              </div>
            </div>
          </>
        )}
      </Body>
    </>
  );
}
